//
// Generated by Bluespec Compiler, version 2018.10.beta1 (build e1df8052c, 2018-10-17)
//
// On Fri Jun 14 15:47:58 IST 2019
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTop(CLK,
	     RST_N);
  input  CLK;
  input  RST_N;

  // inlined wires
  wire start_wire$whas, state_set_pw$whas;

  // register running
  reg running;
  wire running$D_IN, running$EN;

  // register start_reg
  reg start_reg;
  wire start_reg$D_IN, start_reg$EN;

  // register start_reg_1
  reg start_reg_1;
  wire start_reg_1$D_IN, start_reg_1$EN;

  // register state_can_overlap
  reg state_can_overlap;
  wire state_can_overlap$D_IN, state_can_overlap$EN;

  // register state_fired
  reg state_fired;
  wire state_fired$D_IN, state_fired$EN;

  // register state_mkFSMstate
  reg [4 : 0] state_mkFSMstate;
  reg [4 : 0] state_mkFSMstate$D_IN;
  wire state_mkFSMstate$EN;

  // ports of submodule arr
  wire [31 : 0] arr$convs_x,
		arr$weighttran_x,
		arr$winput1_x,
		arr$winput2_x,
		arr$winput3_x,
		arr$winput4_x,
		arr$xinput1_x,
		arr$xinput2_x,
		arr$xinput3_x,
		arr$xinput4_x,
		arr$xinput5_x,
		arr$xinput6_x,
		arr$xinput7_x,
		arr$yinput1_x,
		arr$yinput2_x,
		arr$yinput3_x,
		arr$yinput4_x;
  wire arr$EN_convs,
       arr$EN_weighttran,
       arr$EN_winput1,
       arr$EN_winput2,
       arr$EN_winput3,
       arr$EN_winput4,
       arr$EN_xinput1,
       arr$EN_xinput2,
       arr$EN_xinput3,
       arr$EN_xinput4,
       arr$EN_xinput5,
       arr$EN_xinput6,
       arr$EN_xinput7,
       arr$EN_yinput1,
       arr$EN_yinput2,
       arr$EN_yinput3,
       arr$EN_yinput4;

  // ports of submodule fif
  reg [31 : 0] fif$xfifoin1_x,
	       fif$xfifoin2_x,
	       fif$xfifoin3_x,
	       fif$xfifoin4_x,
	       fif$xfifoin5_x,
	       fif$xfifoin6_x,
	       fif$xfifoin7_x;
  wire [31 : 0] fif$tr_conv_x,
		fif$tr_inputfifo_x,
		fif$tr_outfifo_x,
		fif$tr_weigh_x,
		fif$tr_weightfifo_x,
		fif$wfifoin1_x,
		fif$wfifoin2_x,
		fif$wfifoin3_x,
		fif$wfifoin4_x,
		fif$yfifoin1_x,
		fif$yfifoin2_x,
		fif$yfifoin3_x,
		fif$yfifoin4_x,
		fif$yfifoout1,
		fif$yfifoout2,
		fif$yfifoout3,
		fif$yfifoout4;
  wire fif$EN_tr_conv,
       fif$EN_tr_inputfifo,
       fif$EN_tr_outfifo,
       fif$EN_tr_weigh,
       fif$EN_tr_weightfifo,
       fif$EN_wfifoin1,
       fif$EN_wfifoin2,
       fif$EN_wfifoin3,
       fif$EN_wfifoin4,
       fif$EN_xfifoin1,
       fif$EN_xfifoin2,
       fif$EN_xfifoin3,
       fif$EN_xfifoin4,
       fif$EN_xfifoin5,
       fif$EN_xfifoin6,
       fif$EN_xfifoin7,
       fif$EN_yfifoin1,
       fif$EN_yfifoin2,
       fif$EN_yfifoin3,
       fif$EN_yfifoin4,
       fif$EN_yfifoout1,
       fif$EN_yfifoout2,
       fif$EN_yfifoout3,
       fif$EN_yfifoout4,
       fif$RDY_wfifoin1,
       fif$RDY_wfifoin2,
       fif$RDY_wfifoin3,
       fif$RDY_wfifoin4,
       fif$RDY_xfifoin1,
       fif$RDY_xfifoin2,
       fif$RDY_xfifoin3,
       fif$RDY_xfifoin4,
       fif$RDY_xfifoin5,
       fif$RDY_xfifoin6,
       fif$RDY_xfifoin7,
       fif$RDY_yfifoin1,
       fif$RDY_yfifoin2,
       fif$RDY_yfifoin3,
       fif$RDY_yfifoin4,
       fif$RDY_yfifoout1,
       fif$RDY_yfifoout2,
       fif$RDY_yfifoout3,
       fif$RDY_yfifoout4;

  // rule scheduling signals
  wire WILL_FIRE_RL_action_l583c13,
       WILL_FIRE_RL_action_l594c13,
       WILL_FIRE_RL_action_l625c13,
       WILL_FIRE_RL_action_l649c13,
       WILL_FIRE_RL_action_l664c13,
       WILL_FIRE_RL_action_l679c13,
       WILL_FIRE_RL_action_l694c13,
       WILL_FIRE_RL_action_l708c13,
       WILL_FIRE_RL_action_l719c13,
       WILL_FIRE_RL_action_l730c13,
       WILL_FIRE_RL_fsm_start,
       WILL_FIRE_RL_idle_l582c6;

  // inputs to muxes for submodule ports
  wire MUX_start_reg$write_1__SEL_2;

  // declarations used by system tasks
  // synopsys translate_off
  reg [63 : 0] v__h23561;
  reg [63 : 0] v__h23902;
  reg [63 : 0] v__h24128;
  reg [63 : 0] v__h24358;
  reg [63 : 0] v__h24596;
  reg [63 : 0] v__h25039;
  reg [63 : 0] v__h25304;
  reg [63 : 0] v__h25367;
  reg [63 : 0] v__h25430;
  reg [63 : 0] v__h25493;
  reg [63 : 0] v__h25889;
  reg [63 : 0] v__h26455;
  reg [63 : 0] v__h27025;
  reg [63 : 0] v__h27603;
  reg [63 : 0] v__h28189;
  reg [63 : 0] v__h28504;
  reg [63 : 0] v__h28560;
  reg [63 : 0] v__h28616;
  reg [63 : 0] v__h28663;
  reg [63 : 0] v__h28994;
  reg [63 : 0] v__h29050;
  reg [63 : 0] v__h29106;
  reg [63 : 0] v__h29153;
  reg [63 : 0] v__h29485;
  reg [63 : 0] v__h29541;
  reg [63 : 0] v__h29597;
  reg [63 : 0] v__h29644;
  reg [63 : 0] v__h23265;
  // synopsys translate_on

  // remaining internal signals
  wire abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d149,
       fif_RDY_xfifoin7__2_AND_fif_RDY_xfifoin6__3_AN_ETC___d84,
       fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87,
       fif_RDY_yfifoout4__4_AND_fif_RDY_yfifoout3__5__ETC___d123;

  // submodule arr
  mkPEArray arr(.CLK(CLK),
		.RST_N(RST_N),
		.convs_x(arr$convs_x),
		.weighttran_x(arr$weighttran_x),
		.winput1_x(arr$winput1_x),
		.winput2_x(arr$winput2_x),
		.winput3_x(arr$winput3_x),
		.winput4_x(arr$winput4_x),
		.xinput1_x(arr$xinput1_x),
		.xinput2_x(arr$xinput2_x),
		.xinput3_x(arr$xinput3_x),
		.xinput4_x(arr$xinput4_x),
		.xinput5_x(arr$xinput5_x),
		.xinput6_x(arr$xinput6_x),
		.xinput7_x(arr$xinput7_x),
		.yinput1_x(arr$yinput1_x),
		.yinput2_x(arr$yinput2_x),
		.yinput3_x(arr$yinput3_x),
		.yinput4_x(arr$yinput4_x),
		.EN_xinput1(arr$EN_xinput1),
		.EN_xinput2(arr$EN_xinput2),
		.EN_xinput3(arr$EN_xinput3),
		.EN_xinput4(arr$EN_xinput4),
		.EN_xinput5(arr$EN_xinput5),
		.EN_xinput6(arr$EN_xinput6),
		.EN_xinput7(arr$EN_xinput7),
		.EN_yinput1(arr$EN_yinput1),
		.EN_yinput2(arr$EN_yinput2),
		.EN_yinput3(arr$EN_yinput3),
		.EN_yinput4(arr$EN_yinput4),
		.EN_winput1(arr$EN_winput1),
		.EN_winput2(arr$EN_winput2),
		.EN_winput3(arr$EN_winput3),
		.EN_winput4(arr$EN_winput4),
		.EN_weighttran(arr$EN_weighttran),
		.EN_convs(arr$EN_convs),
		.RDY_xinput1(),
		.RDY_xinput2(),
		.RDY_xinput3(),
		.RDY_xinput4(),
		.RDY_xinput5(),
		.RDY_xinput6(),
		.RDY_xinput7(),
		.RDY_yinput1(),
		.RDY_yinput2(),
		.RDY_yinput3(),
		.RDY_yinput4(),
		.RDY_winput1(),
		.RDY_winput2(),
		.RDY_winput3(),
		.RDY_winput4(),
		.youtput1(),
		.RDY_youtput1(),
		.youtput2(),
		.RDY_youtput2(),
		.youtput3(),
		.RDY_youtput3(),
		.youtput4(),
		.RDY_youtput4(),
		.RDY_weighttran(),
		.RDY_convs());

  // submodule fif
  mkPEFifo fif(.CLK(CLK),
	       .RST_N(RST_N),
	       .tr_conv_x(fif$tr_conv_x),
	       .tr_inputfifo_x(fif$tr_inputfifo_x),
	       .tr_outfifo_x(fif$tr_outfifo_x),
	       .tr_weigh_x(fif$tr_weigh_x),
	       .tr_weightfifo_x(fif$tr_weightfifo_x),
	       .wfifoin1_x(fif$wfifoin1_x),
	       .wfifoin2_x(fif$wfifoin2_x),
	       .wfifoin3_x(fif$wfifoin3_x),
	       .wfifoin4_x(fif$wfifoin4_x),
	       .xfifoin1_x(fif$xfifoin1_x),
	       .xfifoin2_x(fif$xfifoin2_x),
	       .xfifoin3_x(fif$xfifoin3_x),
	       .xfifoin4_x(fif$xfifoin4_x),
	       .xfifoin5_x(fif$xfifoin5_x),
	       .xfifoin6_x(fif$xfifoin6_x),
	       .xfifoin7_x(fif$xfifoin7_x),
	       .yfifoin1_x(fif$yfifoin1_x),
	       .yfifoin2_x(fif$yfifoin2_x),
	       .yfifoin3_x(fif$yfifoin3_x),
	       .yfifoin4_x(fif$yfifoin4_x),
	       .EN_xfifoin1(fif$EN_xfifoin1),
	       .EN_xfifoin2(fif$EN_xfifoin2),
	       .EN_xfifoin3(fif$EN_xfifoin3),
	       .EN_xfifoin4(fif$EN_xfifoin4),
	       .EN_xfifoin5(fif$EN_xfifoin5),
	       .EN_xfifoin6(fif$EN_xfifoin6),
	       .EN_xfifoin7(fif$EN_xfifoin7),
	       .EN_yfifoin1(fif$EN_yfifoin1),
	       .EN_yfifoin2(fif$EN_yfifoin2),
	       .EN_yfifoin3(fif$EN_yfifoin3),
	       .EN_yfifoin4(fif$EN_yfifoin4),
	       .EN_yfifoout1(fif$EN_yfifoout1),
	       .EN_yfifoout2(fif$EN_yfifoout2),
	       .EN_yfifoout3(fif$EN_yfifoout3),
	       .EN_yfifoout4(fif$EN_yfifoout4),
	       .EN_wfifoin1(fif$EN_wfifoin1),
	       .EN_wfifoin2(fif$EN_wfifoin2),
	       .EN_wfifoin3(fif$EN_wfifoin3),
	       .EN_wfifoin4(fif$EN_wfifoin4),
	       .EN_tr_inputfifo(fif$EN_tr_inputfifo),
	       .EN_tr_outfifo(fif$EN_tr_outfifo),
	       .EN_tr_weightfifo(fif$EN_tr_weightfifo),
	       .EN_tr_weigh(fif$EN_tr_weigh),
	       .EN_tr_conv(fif$EN_tr_conv),
	       .RDY_xfifoin1(fif$RDY_xfifoin1),
	       .RDY_xfifoin2(fif$RDY_xfifoin2),
	       .RDY_xfifoin3(fif$RDY_xfifoin3),
	       .RDY_xfifoin4(fif$RDY_xfifoin4),
	       .RDY_xfifoin5(fif$RDY_xfifoin5),
	       .RDY_xfifoin6(fif$RDY_xfifoin6),
	       .RDY_xfifoin7(fif$RDY_xfifoin7),
	       .RDY_yfifoin1(fif$RDY_yfifoin1),
	       .RDY_yfifoin2(fif$RDY_yfifoin2),
	       .RDY_yfifoin3(fif$RDY_yfifoin3),
	       .RDY_yfifoin4(fif$RDY_yfifoin4),
	       .yfifoout1(fif$yfifoout1),
	       .RDY_yfifoout1(fif$RDY_yfifoout1),
	       .yfifoout2(fif$yfifoout2),
	       .RDY_yfifoout2(fif$RDY_yfifoout2),
	       .yfifoout3(fif$yfifoout3),
	       .RDY_yfifoout3(fif$RDY_yfifoout3),
	       .yfifoout4(fif$yfifoout4),
	       .RDY_yfifoout4(fif$RDY_yfifoout4),
	       .RDY_wfifoin1(fif$RDY_wfifoin1),
	       .RDY_wfifoin2(fif$RDY_wfifoin2),
	       .RDY_wfifoin3(fif$RDY_wfifoin3),
	       .RDY_wfifoin4(fif$RDY_wfifoin4),
	       .RDY_tr_inputfifo(),
	       .RDY_tr_outfifo(),
	       .RDY_tr_weightfifo(),
	       .RDY_tr_weigh(),
	       .RDY_tr_conv());

  // rule RL_action_l594c13
  assign WILL_FIRE_RL_action_l594c13 =
	     fif$RDY_wfifoin4 && fif$RDY_wfifoin3 && fif$RDY_wfifoin2 &&
	     fif$RDY_wfifoin1 &&
	     state_mkFSMstate == 5'd2 ;

  // rule RL_action_l625c13
  assign WILL_FIRE_RL_action_l625c13 =
	     fif$RDY_yfifoout4 && fif$RDY_yfifoout3 && fif$RDY_yfifoout2 &&
	     fif$RDY_yfifoout1 &&
	     fif$RDY_yfifoin4 &&
	     fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87 &&
	     state_mkFSMstate == 5'd7 ;

  // rule RL_action_l649c13
  assign WILL_FIRE_RL_action_l649c13 =
	     fif$RDY_yfifoin4 &&
	     fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87 &&
	     state_mkFSMstate == 5'd8 ;

  // rule RL_action_l664c13
  assign WILL_FIRE_RL_action_l664c13 =
	     fif$RDY_yfifoin4 &&
	     fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87 &&
	     state_mkFSMstate == 5'd9 ;

  // rule RL_action_l679c13
  assign WILL_FIRE_RL_action_l679c13 =
	     fif$RDY_yfifoin4 &&
	     fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87 &&
	     state_mkFSMstate == 5'd10 ;

  // rule RL_action_l694c13
  assign WILL_FIRE_RL_action_l694c13 =
	     fif$RDY_yfifoin4 &&
	     fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87 &&
	     state_mkFSMstate == 5'd11 ;

  // rule RL_action_l708c13
  assign WILL_FIRE_RL_action_l708c13 =
	     fif_RDY_yfifoout4__4_AND_fif_RDY_yfifoout3__5__ETC___d123 &&
	     state_mkFSMstate == 5'd12 ;

  // rule RL_action_l719c13
  assign WILL_FIRE_RL_action_l719c13 =
	     fif_RDY_yfifoout4__4_AND_fif_RDY_yfifoout3__5__ETC___d123 &&
	     state_mkFSMstate == 5'd13 ;

  // rule RL_action_l730c13
  assign WILL_FIRE_RL_action_l730c13 =
	     fif_RDY_yfifoout4__4_AND_fif_RDY_yfifoout3__5__ETC___d123 &&
	     state_mkFSMstate == 5'd14 ;

  // rule RL_fsm_start
  assign WILL_FIRE_RL_fsm_start =
	     abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d149 &&
	     start_reg ;

  // rule RL_action_l583c13
  assign WILL_FIRE_RL_action_l583c13 =
	     start_wire$whas &&
	     (state_mkFSMstate == 5'd0 || state_mkFSMstate == 5'd15) ;

  // rule RL_idle_l582c6
  assign WILL_FIRE_RL_idle_l582c6 =
	     !start_wire$whas && state_mkFSMstate == 5'd15 ;

  // inputs to muxes for submodule ports
  assign MUX_start_reg$write_1__SEL_2 =
	     abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d149 &&
	     !start_reg &&
	     !running ;

  // inlined wires
  assign start_wire$whas =
	     WILL_FIRE_RL_fsm_start || start_reg_1 && !state_fired ;
  assign state_set_pw$whas =
	     WILL_FIRE_RL_idle_l582c6 || WILL_FIRE_RL_action_l730c13 ||
	     WILL_FIRE_RL_action_l719c13 ||
	     WILL_FIRE_RL_action_l708c13 ||
	     WILL_FIRE_RL_action_l694c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l625c13 ||
	     state_mkFSMstate == 5'd6 ||
	     state_mkFSMstate == 5'd5 ||
	     state_mkFSMstate == 5'd4 ||
	     state_mkFSMstate == 5'd3 ||
	     WILL_FIRE_RL_action_l594c13 ||
	     state_mkFSMstate == 5'd1 ||
	     WILL_FIRE_RL_action_l583c13 ;

  // register running
  assign running$D_IN = 1'd1 ;
  assign running$EN = MUX_start_reg$write_1__SEL_2 ;

  // register start_reg
  assign start_reg$D_IN = !WILL_FIRE_RL_fsm_start ;
  assign start_reg$EN =
	     WILL_FIRE_RL_fsm_start ||
	     abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d149 &&
	     !start_reg &&
	     !running ;

  // register start_reg_1
  assign start_reg_1$D_IN = start_wire$whas ;
  assign start_reg_1$EN = 1'd1 ;

  // register state_can_overlap
  assign state_can_overlap$D_IN = state_set_pw$whas || state_can_overlap ;
  assign state_can_overlap$EN = 1'd1 ;

  // register state_fired
  assign state_fired$D_IN = state_set_pw$whas ;
  assign state_fired$EN = 1'd1 ;

  // register state_mkFSMstate
  always@(WILL_FIRE_RL_idle_l582c6 or
	  WILL_FIRE_RL_action_l583c13 or
	  state_mkFSMstate or
	  WILL_FIRE_RL_action_l594c13 or
	  WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or
	  WILL_FIRE_RL_action_l694c13 or
	  WILL_FIRE_RL_action_l708c13 or
	  WILL_FIRE_RL_action_l719c13 or WILL_FIRE_RL_action_l730c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_idle_l582c6: state_mkFSMstate$D_IN = 5'd0;
      WILL_FIRE_RL_action_l583c13: state_mkFSMstate$D_IN = 5'd1;
      state_mkFSMstate == 5'd1: state_mkFSMstate$D_IN = 5'd2;
      WILL_FIRE_RL_action_l594c13: state_mkFSMstate$D_IN = 5'd3;
      state_mkFSMstate == 5'd3: state_mkFSMstate$D_IN = 5'd4;
      state_mkFSMstate == 5'd4: state_mkFSMstate$D_IN = 5'd5;
      state_mkFSMstate == 5'd5: state_mkFSMstate$D_IN = 5'd6;
      state_mkFSMstate == 5'd6: state_mkFSMstate$D_IN = 5'd7;
      WILL_FIRE_RL_action_l625c13: state_mkFSMstate$D_IN = 5'd8;
      WILL_FIRE_RL_action_l649c13: state_mkFSMstate$D_IN = 5'd9;
      WILL_FIRE_RL_action_l664c13: state_mkFSMstate$D_IN = 5'd10;
      WILL_FIRE_RL_action_l679c13: state_mkFSMstate$D_IN = 5'd11;
      WILL_FIRE_RL_action_l694c13: state_mkFSMstate$D_IN = 5'd12;
      WILL_FIRE_RL_action_l708c13: state_mkFSMstate$D_IN = 5'd13;
      WILL_FIRE_RL_action_l719c13: state_mkFSMstate$D_IN = 5'd14;
      WILL_FIRE_RL_action_l730c13: state_mkFSMstate$D_IN = 5'd15;
      default: state_mkFSMstate$D_IN = 5'b01010 /* unspecified value */ ;
    endcase
  end
  assign state_mkFSMstate$EN =
	     WILL_FIRE_RL_idle_l582c6 || WILL_FIRE_RL_action_l583c13 ||
	     state_mkFSMstate == 5'd1 ||
	     WILL_FIRE_RL_action_l594c13 ||
	     state_mkFSMstate == 5'd3 ||
	     state_mkFSMstate == 5'd4 ||
	     state_mkFSMstate == 5'd5 ||
	     state_mkFSMstate == 5'd6 ||
	     WILL_FIRE_RL_action_l625c13 ||
	     WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ||
	     WILL_FIRE_RL_action_l708c13 ||
	     WILL_FIRE_RL_action_l719c13 ||
	     WILL_FIRE_RL_action_l730c13 ;

  // submodule arr
  assign arr$convs_x = 32'd1 ;
  assign arr$weighttran_x = (state_mkFSMstate == 5'd6) ? 32'd0 : 32'd1 ;
  assign arr$winput1_x = 32'h0 ;
  assign arr$winput2_x = 32'h0 ;
  assign arr$winput3_x = 32'h0 ;
  assign arr$winput4_x = 32'h0 ;
  assign arr$xinput1_x = 32'h0 ;
  assign arr$xinput2_x = 32'h0 ;
  assign arr$xinput3_x = 32'h0 ;
  assign arr$xinput4_x = 32'h0 ;
  assign arr$xinput5_x = 32'h0 ;
  assign arr$xinput6_x = 32'h0 ;
  assign arr$xinput7_x = 32'h0 ;
  assign arr$yinput1_x = 32'h0 ;
  assign arr$yinput2_x = 32'h0 ;
  assign arr$yinput3_x = 32'h0 ;
  assign arr$yinput4_x = 32'h0 ;
  assign arr$EN_xinput1 = 1'b0 ;
  assign arr$EN_xinput2 = 1'b0 ;
  assign arr$EN_xinput3 = 1'b0 ;
  assign arr$EN_xinput4 = 1'b0 ;
  assign arr$EN_xinput5 = 1'b0 ;
  assign arr$EN_xinput6 = 1'b0 ;
  assign arr$EN_xinput7 = 1'b0 ;
  assign arr$EN_yinput1 = 1'b0 ;
  assign arr$EN_yinput2 = 1'b0 ;
  assign arr$EN_yinput3 = 1'b0 ;
  assign arr$EN_yinput4 = 1'b0 ;
  assign arr$EN_winput1 = 1'b0 ;
  assign arr$EN_winput2 = 1'b0 ;
  assign arr$EN_winput3 = 1'b0 ;
  assign arr$EN_winput4 = 1'b0 ;
  assign arr$EN_weighttran =
	     state_mkFSMstate == 5'd6 || state_mkFSMstate == 5'd1 ;
  assign arr$EN_convs = state_mkFSMstate == 5'd6 ;

  // submodule fif
  assign fif$tr_conv_x = 32'd1 ;
  assign fif$tr_inputfifo_x = 32'd1 ;
  assign fif$tr_outfifo_x = 32'd1 ;
  assign fif$tr_weigh_x = (state_mkFSMstate == 5'd6) ? 32'd0 : 32'd1 ;
  assign fif$tr_weightfifo_x = (state_mkFSMstate == 5'd6) ? 32'd0 : 32'd1 ;
  assign fif$wfifoin1_x = 32'd1 ;
  assign fif$wfifoin2_x = 32'd1 ;
  assign fif$wfifoin3_x = 32'd1 ;
  assign fif$wfifoin4_x = 32'd1 ;
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin1_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin1_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin1_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin1_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin1_x = 32'd5;
      default: fif$xfifoin1_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin2_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin2_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin2_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin2_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin2_x = 32'd5;
      default: fif$xfifoin2_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin3_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin3_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin3_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin3_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin3_x = 32'd5;
      default: fif$xfifoin3_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin4_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin4_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin4_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin4_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin4_x = 32'd5;
      default: fif$xfifoin4_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin5_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin5_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin5_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin5_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin5_x = 32'd5;
      default: fif$xfifoin5_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin6_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin6_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin6_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin6_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin6_x = 32'd5;
      default: fif$xfifoin6_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  always@(WILL_FIRE_RL_action_l625c13 or
	  WILL_FIRE_RL_action_l649c13 or
	  WILL_FIRE_RL_action_l664c13 or
	  WILL_FIRE_RL_action_l679c13 or WILL_FIRE_RL_action_l694c13)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_action_l625c13: fif$xfifoin7_x = 32'd1;
      WILL_FIRE_RL_action_l649c13: fif$xfifoin7_x = 32'd2;
      WILL_FIRE_RL_action_l664c13: fif$xfifoin7_x = 32'd3;
      WILL_FIRE_RL_action_l679c13: fif$xfifoin7_x = 32'd4;
      WILL_FIRE_RL_action_l694c13: fif$xfifoin7_x = 32'd5;
      default: fif$xfifoin7_x = 32'hAAAAAAAA /* unspecified value */ ;
    endcase
  end
  assign fif$yfifoin1_x = 32'd0 ;
  assign fif$yfifoin2_x = 32'd0 ;
  assign fif$yfifoin3_x = 32'd0 ;
  assign fif$yfifoin4_x = 32'd0 ;
  assign fif$EN_xfifoin1 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_xfifoin2 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_xfifoin3 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_xfifoin4 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_xfifoin5 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_xfifoin6 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_xfifoin7 =
	     WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l694c13 ;
  assign fif$EN_yfifoin1 =
	     WILL_FIRE_RL_action_l694c13 || WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoin2 =
	     WILL_FIRE_RL_action_l694c13 || WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoin3 =
	     WILL_FIRE_RL_action_l694c13 || WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoin4 =
	     WILL_FIRE_RL_action_l694c13 || WILL_FIRE_RL_action_l679c13 ||
	     WILL_FIRE_RL_action_l664c13 ||
	     WILL_FIRE_RL_action_l649c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoout1 =
	     WILL_FIRE_RL_action_l730c13 || WILL_FIRE_RL_action_l719c13 ||
	     WILL_FIRE_RL_action_l708c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoout2 =
	     WILL_FIRE_RL_action_l730c13 || WILL_FIRE_RL_action_l719c13 ||
	     WILL_FIRE_RL_action_l708c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoout3 =
	     WILL_FIRE_RL_action_l730c13 || WILL_FIRE_RL_action_l719c13 ||
	     WILL_FIRE_RL_action_l708c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_yfifoout4 =
	     WILL_FIRE_RL_action_l730c13 || WILL_FIRE_RL_action_l719c13 ||
	     WILL_FIRE_RL_action_l708c13 ||
	     WILL_FIRE_RL_action_l625c13 ;
  assign fif$EN_wfifoin1 = WILL_FIRE_RL_action_l594c13 ;
  assign fif$EN_wfifoin2 = WILL_FIRE_RL_action_l594c13 ;
  assign fif$EN_wfifoin3 = WILL_FIRE_RL_action_l594c13 ;
  assign fif$EN_wfifoin4 = WILL_FIRE_RL_action_l594c13 ;
  assign fif$EN_tr_inputfifo = state_mkFSMstate == 5'd6 ;
  assign fif$EN_tr_outfifo = state_mkFSMstate == 5'd6 ;
  assign fif$EN_tr_weightfifo =
	     state_mkFSMstate == 5'd6 || state_mkFSMstate == 5'd1 ;
  assign fif$EN_tr_weigh =
	     state_mkFSMstate == 5'd6 || state_mkFSMstate == 5'd1 ;
  assign fif$EN_tr_conv = state_mkFSMstate == 5'd6 ;

  // remaining internal signals
  assign abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d149 =
	     (state_mkFSMstate == 5'd0 || state_mkFSMstate == 5'd15) &&
	     (!start_reg_1 || state_fired) ;
  assign fif_RDY_xfifoin7__2_AND_fif_RDY_xfifoin6__3_AN_ETC___d84 =
	     fif$RDY_xfifoin7 && fif$RDY_xfifoin6 && fif$RDY_xfifoin5 &&
	     fif$RDY_xfifoin4 &&
	     fif$RDY_xfifoin3 &&
	     fif$RDY_xfifoin2 &&
	     fif$RDY_xfifoin1 ;
  assign fif_RDY_yfifoin3__9_AND_fif_RDY_yfifoin2__0_AN_ETC___d87 =
	     fif$RDY_yfifoin3 && fif$RDY_yfifoin2 && fif$RDY_yfifoin1 &&
	     fif_RDY_xfifoin7__2_AND_fif_RDY_xfifoin6__3_AN_ETC___d84 ;
  assign fif_RDY_yfifoout4__4_AND_fif_RDY_yfifoout3__5__ETC___d123 =
	     fif$RDY_yfifoout4 && fif$RDY_yfifoout3 && fif$RDY_yfifoout2 &&
	     fif$RDY_yfifoout1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        running <= `BSV_ASSIGNMENT_DELAY 1'd0;
	start_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	start_reg_1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state_can_overlap <= `BSV_ASSIGNMENT_DELAY 1'd1;
	state_fired <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state_mkFSMstate <= `BSV_ASSIGNMENT_DELAY 5'd0;
      end
    else
      begin
        if (running$EN) running <= `BSV_ASSIGNMENT_DELAY running$D_IN;
	if (start_reg$EN) start_reg <= `BSV_ASSIGNMENT_DELAY start_reg$D_IN;
	if (start_reg_1$EN)
	  start_reg_1 <= `BSV_ASSIGNMENT_DELAY start_reg_1$D_IN;
	if (state_can_overlap$EN)
	  state_can_overlap <= `BSV_ASSIGNMENT_DELAY state_can_overlap$D_IN;
	if (state_fired$EN)
	  state_fired <= `BSV_ASSIGNMENT_DELAY state_fired$D_IN;
	if (state_mkFSMstate$EN)
	  state_mkFSMstate <= `BSV_ASSIGNMENT_DELAY state_mkFSMstate$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    running = 1'h0;
    start_reg = 1'h0;
    start_reg_1 = 1'h0;
    state_can_overlap = 1'h0;
    state_fired = 1'h0;
    state_mkFSMstate = 5'h0A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd1)
	begin
	  v__h23561 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd1)
	$display("%t Weight Transfer to Fifo", v__h23561);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l594c13)
	begin
	  v__h23902 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l594c13)
	$display("%t Weight transfer to PEArray", v__h23902);
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd3)
	begin
	  v__h24128 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd3)
	$display("%t Weight transfer 1", v__h24128);
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd4)
	begin
	  v__h24358 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd4)
	$display("%t Weight transfer 2", v__h24358);
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd5)
	begin
	  v__h24596 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd5)
	$display("%t Weight transfer 3", v__h24596);
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd6)
	begin
	  v__h25039 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd6)
	$display("%t Weight transfer ended", v__h25039);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	begin
	  v__h25304 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	$display("%t y11 = %0d", v__h25304, fif$yfifoout1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	begin
	  v__h25367 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	$display("%t y12 = %0d", v__h25367, fif$yfifoout2);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	begin
	  v__h25430 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	$display("%t y13 = %0d", v__h25430, fif$yfifoout3);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	begin
	  v__h25493 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	$display("%t y14 = %0d", v__h25493, fif$yfifoout4);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	begin
	  v__h25889 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13)
	$display("%t Conv fifo started", v__h25889);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l649c13)
	begin
	  v__h26455 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l649c13) $display("%t Conv cycle 1", v__h26455);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l664c13)
	begin
	  v__h27025 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l664c13) $display("%t Conv cycle 2", v__h27025);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l679c13)
	begin
	  v__h27603 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l679c13) $display("%t Conv cycle 3", v__h27603);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l694c13)
	begin
	  v__h28189 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l694c13) $display("%t Conv cycle 4", v__h28189);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	begin
	  v__h28504 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	$display("%t y11 = %0d", v__h28504, fif$yfifoout1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	begin
	  v__h28560 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	$display("%t y12 = %0d", v__h28560, fif$yfifoout2);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	begin
	  v__h28616 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	$display("%t y13 = %0d", v__h28616, fif$yfifoout3);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	begin
	  v__h28663 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13)
	$display("%t y14 = %0d", v__h28663, fif$yfifoout4);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	begin
	  v__h28994 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	$display("%t y11 = %0d", v__h28994, fif$yfifoout1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	begin
	  v__h29050 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	$display("%t y12 = %0d", v__h29050, fif$yfifoout2);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	begin
	  v__h29106 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	$display("%t y13 = %0d", v__h29106, fif$yfifoout3);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	begin
	  v__h29153 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13)
	$display("%t y14 = %0d", v__h29153, fif$yfifoout4);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	begin
	  v__h29485 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	$display("%t y11 = %0d", v__h29485, fif$yfifoout1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	begin
	  v__h29541 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	$display("%t y12 = %0d", v__h29541, fif$yfifoout2);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	begin
	  v__h29597 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	$display("%t y13 = %0d", v__h29597, fif$yfifoout3);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	begin
	  v__h29644 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l730c13)
	$display("%t y14 = %0d", v__h29644, fif$yfifoout4);
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd1 &&
	  (WILL_FIRE_RL_action_l594c13 || state_mkFSMstate == 5'd3 ||
	   state_mkFSMstate == 5'd4 ||
	   state_mkFSMstate == 5'd5 ||
	   state_mkFSMstate == 5'd6 ||
	   WILL_FIRE_RL_action_l625c13 ||
	   WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 587, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l587c13] and\n  [RL_action_l594c13, RL_action_l602c13, RL_action_l606c13, RL_action_l610c13,\n  RL_action_l614c13, RL_action_l625c13, RL_action_l649c13, RL_action_l664c13,\n  RL_action_l679c13, RL_action_l694c13, RL_action_l708c13, RL_action_l719c13,\n  RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l594c13 &&
	  (state_mkFSMstate == 5'd3 || state_mkFSMstate == 5'd4 ||
	   state_mkFSMstate == 5'd5 ||
	   state_mkFSMstate == 5'd6 ||
	   WILL_FIRE_RL_action_l625c13 ||
	   WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 594, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l594c13] and\n  [RL_action_l602c13, RL_action_l606c13, RL_action_l610c13, RL_action_l614c13,\n  RL_action_l625c13, RL_action_l649c13, RL_action_l664c13, RL_action_l679c13,\n  RL_action_l694c13, RL_action_l708c13, RL_action_l719c13, RL_action_l730c13]\n  ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd3 &&
	  (state_mkFSMstate == 5'd4 || state_mkFSMstate == 5'd5 ||
	   state_mkFSMstate == 5'd6 ||
	   WILL_FIRE_RL_action_l625c13 ||
	   WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 602, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l602c13] and\n  [RL_action_l606c13, RL_action_l610c13, RL_action_l614c13, RL_action_l625c13,\n  RL_action_l649c13, RL_action_l664c13, RL_action_l679c13, RL_action_l694c13,\n  RL_action_l708c13, RL_action_l719c13, RL_action_l730c13] ) fired in the same\n  clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd4 &&
	  (state_mkFSMstate == 5'd5 || state_mkFSMstate == 5'd6 ||
	   WILL_FIRE_RL_action_l625c13 ||
	   WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 606, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l606c13] and\n  [RL_action_l610c13, RL_action_l614c13, RL_action_l625c13, RL_action_l649c13,\n  RL_action_l664c13, RL_action_l679c13, RL_action_l694c13, RL_action_l708c13,\n  RL_action_l719c13, RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd5 &&
	  (state_mkFSMstate == 5'd6 || WILL_FIRE_RL_action_l625c13 ||
	   WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 610, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l610c13] and\n  [RL_action_l614c13, RL_action_l625c13, RL_action_l649c13, RL_action_l664c13,\n  RL_action_l679c13, RL_action_l694c13, RL_action_l708c13, RL_action_l719c13,\n  RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l625c13 &&
	  (WILL_FIRE_RL_action_l649c13 || WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 625, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l625c13] and\n  [RL_action_l649c13, RL_action_l664c13, RL_action_l679c13, RL_action_l694c13,\n  RL_action_l708c13, RL_action_l719c13, RL_action_l730c13] ) fired in the same\n  clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (state_mkFSMstate == 5'd6 &&
	  (WILL_FIRE_RL_action_l625c13 || WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 614, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l614c13] and\n  [RL_action_l625c13, RL_action_l649c13, RL_action_l664c13, RL_action_l679c13,\n  RL_action_l694c13, RL_action_l708c13, RL_action_l719c13, RL_action_l730c13]\n  ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l649c13 &&
	  (WILL_FIRE_RL_action_l664c13 || WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 649, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l649c13] and\n  [RL_action_l664c13, RL_action_l679c13, RL_action_l694c13, RL_action_l708c13,\n  RL_action_l719c13, RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l664c13 &&
	  (WILL_FIRE_RL_action_l679c13 || WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 664, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l664c13] and\n  [RL_action_l679c13, RL_action_l694c13, RL_action_l708c13, RL_action_l719c13,\n  RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l694c13 &&
	  (WILL_FIRE_RL_action_l708c13 || WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 694, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l694c13] and\n  [RL_action_l708c13, RL_action_l719c13, RL_action_l730c13] ) fired in the\n  same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l679c13 &&
	  (WILL_FIRE_RL_action_l694c13 || WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 679, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l679c13] and\n  [RL_action_l694c13, RL_action_l708c13, RL_action_l719c13, RL_action_l730c13]\n  ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l708c13 &&
	  (WILL_FIRE_RL_action_l719c13 || WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 708, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l708c13] and\n  [RL_action_l719c13, RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l719c13 && WILL_FIRE_RL_action_l730c13)
	$display("Error: \"TestModule.bsv\", line 719, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l719c13] and\n  [RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l583c13)
	begin
	  v__h23265 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l583c13) $display("%t blah", v__h23265);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_action_l583c13 &&
	  (state_mkFSMstate == 5'd1 || WILL_FIRE_RL_action_l594c13 ||
	   state_mkFSMstate == 5'd3 ||
	   state_mkFSMstate == 5'd4 ||
	   state_mkFSMstate == 5'd5 ||
	   state_mkFSMstate == 5'd6 ||
	   WILL_FIRE_RL_action_l625c13 ||
	   WILL_FIRE_RL_action_l649c13 ||
	   WILL_FIRE_RL_action_l664c13 ||
	   WILL_FIRE_RL_action_l679c13 ||
	   WILL_FIRE_RL_action_l694c13 ||
	   WILL_FIRE_RL_action_l708c13 ||
	   WILL_FIRE_RL_action_l719c13 ||
	   WILL_FIRE_RL_action_l730c13))
	$display("Error: \"TestModule.bsv\", line 583, column 13: (R0001)\n  Mutually exclusive rules (from the ME sets [RL_action_l583c13] and\n  [RL_action_l587c13, RL_action_l594c13, RL_action_l602c13, RL_action_l606c13,\n  RL_action_l610c13, RL_action_l614c13, RL_action_l625c13, RL_action_l649c13,\n  RL_action_l664c13, RL_action_l679c13, RL_action_l694c13, RL_action_l708c13,\n  RL_action_l719c13, RL_action_l730c13] ) fired in the same clock cycle.\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (running &&
	  abort_whas_AND_abort_wget_OR_state_mkFSMstate__ETC___d149 &&
	  !start_reg)
	$finish(32'd0);
  end
  // synopsys translate_on
endmodule  // mkTop

